export const LAST_FM_INIT_SEARCH = 'LAST_FM_INIT_SEARCH';

export const LAST_FM_FETCH_START = 'LAST_FM_FETCH_START';
export const LAST_FM_FETCH_SUCCESS='LAST_FM_FETCH_SUCCESS';
export const LAST_FM_FETCH_ERROR='LAST_FM_FETCH_ERROR';


export const M_BRAINZ_INIT_SEARCH = 'M_BRAINZ_INIT_SEARCH';

export const M_BRAINZ_FETCH_START = 'M_BRAINZ_FETCH_START';
export const M_BRAINZ_FETCH_SUCCESS='M_BRAINZ_FETCH_SUCCESS';
export const M_BRAINZ_FETCH_ERROR = 'M_BRAINZ_FETCH_ERROR';

export const INIT_SEARCH_RELEASE = 'INIT_SEARCH_RELEASE';
export const FETCH_RELEASE_START = 'FETCH_RELEASE_START';
export const FETCH_RELEASE_SUCCESS = 'FETCH_RELEASE_SUCCESS';
export const FETCH_RELEASE_ERROR = 'FETCH_RELEASE_ERROR';

export const ADD_FAV_ARTISTE = 'ADD_FAV_ARTISTE';
export const REMOVE_FAV_ARTISTE = 'REMOVE_FAV_ARTISTE';

export const ADD_FAV_RELEASE = 'ADD_FAV_RELEASE';
export const REMOVE_FAV_RELEASE = 'REMOVE_FAV_RELEASE';

export const SET_FAV_ARTISTS = 'SET_FAV_ARTISTS';
export const SET_FAV_ARTISTS_SUCCESS = 'SET_FAV_ARTISTS_SUCCESS';

export const SET_FAV_RELEASES = 'SET_FAV_RELEASES';
export const SET_FAV_RELEASES_SUCCESS = 'SET_FAV_RELEASES_SUCCESS';




